name: Feature Request
description: Request a new feature.
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you add to the Starter Kit?
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!